insert into TB_LIVRO(TITULO, DESCRICAO, ISBN, AUTOR, EDITORA, ANO_PUBLICACAO, FK_CATEGORIA) values ('O Senhor dos Anéis', 'O Senhor dos Anéis é uma trilogia de livros de fantasia escrita por J. R. R. Tolkien. A trilogia é composta por O Hobbit, O Senhor dos Anéis e O Retorno do Rei. A história se passa na Terra-média, um mundo fictício criado por Tolkien, e conta a jornada de um grupo de anões, hobbits, elfos e homens para destruir o Um Anel, um artefato mágico que foi criado pelo Sauron, um poderoso mago, e que foi roubado por seu antecessor, o Senhor das Trevas, o Rei dos Anões, o Rei dos Elfos e o Rei dos Homens.', '978-85-359-0277-5', 'J. R. R. Tolkien', 'Martins Fontes', 1954, 1);
insert into TB_LIVRO(TITULO, DESCRICAO, ISBN, AUTOR, EDITORA, ANO_PUBLICACAO, FK_CATEGORIA) values ('O Pequeno Príncipe', 'O Pequeno Príncipe é um livro de Antoine de Saint-Exupéry, publicado em 1943. O livro conta a história de um piloto que se encontra perdido no deserto do Saara e encontra um pequeno príncipe que vem de um planeta distante. O livro é considerado um clássico da literatura francesa e mundial.', '978-85-359-0277-5', 'Antoine de Saint-Exupéry', 'Martins Fontes', 1943, 1);
insert into TB_LIVRO(TITULO, DESCRICAO, ISBN, AUTOR, EDITORA, ANO_PUBLICACAO, FK_CATEGORIA) values ('O Código da Vinci', 'O Código da Vinci é um romance policial escrito pelo autor britânico Dan Brown. O livro foi publicado em 2003 e se tornou um best-seller internacional, vendendo mais de 80 milhões de cópias em todo o mundo. O livro é o primeiro de uma trilogia que inclui O Código da Vinci, Anjos e Demônios e O Símbolo Perdido.', '978-85-359-0277-5', 'Dan Brown', 'Martins Fontes', 2003, 2);
insert into TB_LIVRO(TITULO, DESCRICAO, ISBN, AUTOR, EDITORA, ANO_PUBLICACAO, FK_CATEGORIA) values ('O Diário de Anne Frank', 'O Diário de Anne Frank é um livro escrito por Anne Frank, uma garota judia que viveu na Holanda durante a Segunda Guerra Mundial. O livro é uma compilação de trechos do diário que Anne escreveu enquanto estava escondida com sua família e outros judeus na casa de um amigo de seus pais, Otto Frank, em Amsterdã.', '978-85-359-0277-5', 'Anne Frank', 'Martins Fontes', 1947, 2);
insert into TB_LIVRO(TITULO, DESCRICAO, ISBN, AUTOR, EDITORA, ANO_PUBLICACAO, FK_CATEGORIA) values ('A Culpa é das Estrelas', 'A Culpa é das Estrelas é um romance de John Green, publicado em 2012. O livro conta a história de Hazel Grace Lancaster, uma garota de 16 anos que tem câncer de pulmão e se apaixona por Augustus Waters, um garoto de 17 anos que perdeu uma perna em um acidente de bicicleta.', '978-85-359-0277-5', 'John Green', 'Martins Fontes', 2012, 4);

insert into TB_LIVRO(TITULO, DESCRICAO, ISBN, AUTOR, EDITORA, ANO_PUBLICACAO, FK_CATEGORIA) values ('Java Como Programar', 'Java Como Programar é um livro de programação escrito por Deitel e Deitel. O livro é uma introdução à linguagem de programação Java e é voltado para estudantes de cursos de ciência da computação e engenharia de computação.', '978-85-359-0277-5', 'Deitel e Deitel', 'Martins Fontes', 2007, 3);
insert into TB_LIVRO(TITULO, DESCRICAO, ISBN, AUTOR, EDITORA, ANO_PUBLICACAO, FK_CATEGORIA) values ('C# Como Programar', 'C# Como Programar é um livro de programação escrito por Deitel e Deitel. O livro é uma introdução à linguagem de programação C# e é voltado para estudantes de cursos de ciência da computação e engenharia de computação.', '978-85-359-0277-5', 'Deitel e Deitel', 'Martins Fontes', 2008, 3);
insert into TB_LIVRO(TITULO, DESCRICAO, ISBN, AUTOR, EDITORA, ANO_PUBLICACAO, FK_CATEGORIA) values ('PHP Como Programar', 'PHP Como Programar é um livro de programação escrito por Deitel e Deitel. O livro é uma introdução à linguagem de programação PHP e é voltado para estudantes de cursos de ciência da computação e engenharia de computação.', '978-85-359-0277-5', 'Deitel e Deitel', 'Martins Fontes', 2009, 3);
insert into TB_LIVRO(TITULO, DESCRICAO, ISBN, AUTOR, EDITORA, ANO_PUBLICACAO, FK_CATEGORIA) values ('HTML5 e CSS3', 'HTML5 e CSS3 é um livro de programação escrito por Deitel e Deitel. O livro é uma introdução à linguagem de programação HTML5 e CSS3 e é voltado para estudantes de cursos de ciência da computação e engenharia de computação.', '978-85-359-0277-5', 'Deitel e Deitel', 'Martins Fontes', 2010, 3);
insert into TB_LIVRO(TITULO, DESCRICAO, ISBN, AUTOR, EDITORA, ANO_PUBLICACAO, FK_CATEGORIA) values ('JavaScript e Jquery', 'JavaScript e Jquery é um livro de programação escrito por Deitel e Deitel. O livro é uma introdução à linguagem de programação JavaScript e Jquery e é voltado para estudantes de cursos de ciência da computação e engenharia de computação.', '978-85-359-0277-5', 'Deitel e Deitel', 'Martins Fontes', 2011, 3);
insert into TB_LIVRO(TITULO, DESCRICAO, ISBN, AUTOR, EDITORA, ANO_PUBLICACAO, FK_CATEGORIA) values ('Android Como Programar', 'Android Como Programar é um livro de programação escrito por Deitel e Deitel. O livro é uma introdução à linguagem de programação Android e é voltado para estudantes de cursos de ciência da computação e engenharia de computação.', '978-85-359-0277-5', 'Deitel e Deitel', 'Martins Fontes', 2012, 3);

insert into TB_LIVRO(TITULO, DESCRICAO, ISBN, AUTOR, EDITORA, ANO_PUBLICACAO, FK_CATEGORIA) values ('A Origem das Espécies', 'A Origem das Espécies é um livro de Charles Darwin, publicado em 1859. O livro é uma explicação da evolução das espécies por meio da seleção natural. O livro é considerado um clássico da literatura científica e mundial.', '978-85-359-0277-5', 'Charles Darwin', 'Martins Fontes', 1859, 5);
insert into TB_LIVRO(TITULO, DESCRICAO, ISBN, AUTOR, EDITORA, ANO_PUBLICACAO, FK_CATEGORIA) values ('O Princípio da Incerteza', 'O Princípio da Incerteza é um livro de Stephen Hawking, publicado em 2002. O livro é uma explicação da evolução das espécies por meio da seleção natural. O livro é considerado um clássico da literatura científica e mundial.', '978-85-359-0277-5', 'Stephen Hawking', 'Martins Fontes', 2002, 5);
insert into TB_LIVRO(TITULO, DESCRICAO, ISBN, AUTOR, EDITORA, ANO_PUBLICACAO, FK_CATEGORIA) values ('O Universo em uma Casca de Noz', 'O Universo em uma Casca de Noz é um livro de Stephen Hawking, publicado em 2001. O livro é uma explicação da evolução das espécies por meio da seleção natural. O livro é considerado um clássico da literatura científica e mundial.', '978-85-359-0277-5', 'Stephen Hawking', 'Martins Fontes', 2001, 5);
insert into TB_LIVRO(TITULO, DESCRICAO, ISBN, AUTOR, EDITORA, ANO_PUBLICACAO, FK_CATEGORIA) values ('O Cérebro de Broca', 'O Cérebro de Broca é um livro de Stephen Hawking, publicado em 2003. O livro é uma explicação da evolução das espécies por meio da seleção natural. O livro é considerado um clássico da literatura científica e mundial.', '978-85-359-0277-5', 'Stephen Hawking', 'Martins Fontes', 2003, 5);
insert into TB_LIVRO(TITULO, DESCRICAO, ISBN, AUTOR, EDITORA, ANO_PUBLICACAO, FK_CATEGORIA) values ('O Cérebro de Darwin', 'O Cérebro de Darwin é um livro de Stephen Hawking, publicado em 2004. O livro é uma explicação da evolução das espécies por meio da seleção natural. O livro é considerado um clássico da literatura científica e mundial.', '978-85-359-0277-5', 'Stephen Hawking', 'Martins Fontes', 2004, 5);
insert into TB_LIVRO(TITULO, DESCRICAO, ISBN, AUTOR, EDITORA, ANO_PUBLICACAO, FK_CATEGORIA) values ('O Cérebro de Einstein', 'O Cérebro de Einstein é um livro de Stephen Hawking, publicado em 2005. O livro é uma explicação da evolução das espécies por meio da seleção natural. O livro é considerado um clássico da literatura científica e mundial.', '978-85-359-0277-5', 'Stephen Hawking', 'Martins Fontes', 2005, 5);
insert into TB_LIVRO(TITULO, DESCRICAO, ISBN, AUTOR, EDITORA, ANO_PUBLICACAO, FK_CATEGORIA) values ('O Cérebro de Newton', 'O Cérebro de Newton é um livro de Stephen Hawking, publicado em 2006. O livro é uma explicação da evolução das espécies por meio da seleção natural. O livro é considerado um clássico da literatura científica e mundial.', '978-85-359-0277-5', 'Stephen Hawking', 'Martins Fontes', 2006, 5);
insert into TB_LIVRO(TITULO, DESCRICAO, ISBN, AUTOR, EDITORA, ANO_PUBLICACAO, FK_CATEGORIA) values ('O Cérebro de Tesla', 'O Cérebro de Tesla é um livro de Stephen Hawking, publicado em 2007. O livro é uma explicação da evolução das espécies por meio da seleção natural. O livro é considerado um clássico da literatura científica e mundial.', '978-85-359-0277-5', 'Stephen Hawking', 'Martins Fontes', 2007, 5);
insert into TB_LIVRO(TITULO, DESCRICAO, ISBN, AUTOR, EDITORA, ANO_PUBLICACAO, FK_CATEGORIA) values ('O Cérebro de Turing', 'O Cérebro de Turing é um livro de Stephen Hawking, publicado em 2008. O livro é uma explicação da evolução das espécies por meio da seleção natural. O livro é considerado um clássico da literatura científica e mundial.', '978-85-359-0277-5', 'Stephen Hawking', 'Martins Fontes', 2008, 5);
insert into TB_LIVRO(TITULO, DESCRICAO, ISBN, AUTOR, EDITORA, ANO_PUBLICACAO, FK_CATEGORIA) values ('O Cérebro de Watson', 'O Cérebro de Watson é um livro de Stephen Hawking, publicado em 2009. O livro é uma explicação da evolução das espécies por meio da seleção natural. O livro é considerado um clássico da literatura científica e mundial.', '978-85-359-0277-5', 'Stephen Hawking', 'Martins Fontes', 2009, 5);